language: python
python:
  - "2.7"

install: pip install -r requirements.txt

script:
  - coverage run --source=pysigep setup.py test
  - nosetests --with-doctest --doctest-extension=py
  - coverage run --source=pysigep setup.py test

after_success:
  - coveralls
